name: auto update

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
    inputs:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Get last version
        id: used_version
        uses: fopina/docker-postfix-relay/.github/actions/docker-apk-version@587173caaa0614a23130856565202d30870c62fc
        with:
          image: fopina/wireguard:latest
          package: wireguard-tools

      - name: Get latest version
        id: latest_version
        uses: fopina/docker-postfix-relay/.github/actions/docker-apk-version@587173caaa0614a23130856565202d30870c62fc
        with:
          image: alpine:latest
          package: wireguard-tools
          install: true

      - name: Check for any new
        if: steps.used_version.outputs.version != steps.latest_version.outputs.version
        run: |
            echo "### New Version" >> $GITHUB_STEP_SUMMARY
            echo wireguard-tools version updated from ${{ steps.used_version.outputs.version }} to ${{ steps.latest_version.outputs.version }} >> $GITHUB_STEP_SUMMARY
            exit 1
