name: publish to dockerhub

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: |
            test-build

      - name: Check version
        id: this_version
        uses: fopina/docker-postfix-relay/.github/actions/docker-apk-version@f637576f44c06509e69afe61779fe1b9a2921da7
        with:
          image: test-build
          package: wireguard-tools

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            fopina/wireguard:${{ steps.this_version.outputs.version }}
            ghcr.io/fopina/wireguard:${{ steps.this_version.outputs.version }}
            fopina/wireguard:${{ steps.this_version.outputs.version }}-${{ github.run_number }}
            ghcr.io/fopina/wireguard:${{ steps.this_version.outputs.version }}-${{ github.run_number }}
            fopina/wireguard:latest
            ghcr.io/fopina/wireguard:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Check for any new
        run: |
            echo "### Published" >> $GITHUB_STEP_SUMMARY
            echo "`fopina/wireguard:${{ steps.this_version.outputs.version }}-${{ github.run_number }}`" >> $GITHUB_STEP_SUMMARY
            echo "`ghcr.io/fopina/wireguard:${{ steps.this_version.outputs.version }}-${{ github.run_number }}`" >> $GITHUB_STEP_SUMMARY
